In [11]:
import numpy as np
arr=np.array([0,1,2,3,4])
arr.size
arr.dtype
arr.shape:(5,)
arr

array([0, 1, 2, 3, 4])

In [23]:
c=[]
for i in range(len(arr)):
    c.append(i+2)
c    

[2, 3, 4, 5, 6]

In [19]:
d=[]
for i in range(len(arr)):
    d.append(i*2)
d    

[0, 2, 4, 6, 8]

In [25]:
e=[]
for i in range(len(arr)):
    e.append(i/2)
e    

[0.0, 0.5, 1.0, 1.5, 2.0]

In [29]:
import numpy as np
arr=np.array([1,2,3,6,4,5])
rev_arr=arr[::-1]
rev_arr

array([5, 4, 6, 3, 2, 1])

In [31]:
x=np.array([1,2,3,4,5,1,2,1,1,1])
def most_frequent_value(arr):
    unique_values,counts=np.unique(arr,return_counts=True)
    max_count=np.max(counts)
    most_frequent=unique_values[np.argmax(counts)]
    indices=np.where(arr==most_frequent)[0]
    return most_frequent,indices

most_frequent_x,indices_x=most_frequent_value(x)
print("Most frequent value: ",most_frequent_x,"Indices: ",indices_x)

Most frequent value:  1 Indices:  [0 5 7 8 9]


In [33]:
y=np.array([1,1,1,2,3,4,2,4,3,3])
most_frequent_y,indices_y=most_frequent_value(y)
print("Most frequent value: ",most_frequent_y,"Indices: ",indices_y)

Most frequent value:  1 Indices:  [0 1 2]


In [39]:
arr=np.array([[10,20,30],[40,50,60],[70,80,90]])
print(arr[0][1])

20


In [41]:
print(arr[2][0])

70


In [45]:
priyam=np.linspace(10,100,25)
print(priyam)

[ 10.    13.75  17.5   21.25  25.    28.75  32.5   36.25  40.    43.75
  47.5   51.25  55.    58.75  62.5   66.25  70.    73.75  77.5   81.25
  85.    88.75  92.5   96.25 100.  ]


In [47]:
print(priyam.ndim)

1


In [49]:
print(priyam.shape)

(25,)


In [51]:
print(priyam.size)

25


In [53]:
print(priyam.dtype)

float64


In [55]:
print(priyam.nbytes)

200


In [63]:
priyam_reshaped=priyam.reshape(25,1)
print(priyam_reshaped)

[[ 10.  ]
 [ 13.75]
 [ 17.5 ]
 [ 21.25]
 [ 25.  ]
 [ 28.75]
 [ 32.5 ]
 [ 36.25]
 [ 40.  ]
 [ 43.75]
 [ 47.5 ]
 [ 51.25]
 [ 55.  ]
 [ 58.75]
 [ 62.5 ]
 [ 66.25]
 [ 70.  ]
 [ 73.75]
 [ 77.5 ]
 [ 81.25]
 [ 85.  ]
 [ 88.75]
 [ 92.5 ]
 [ 96.25]
 [100.  ]]


In [65]:
priyam_T=priyam.T
print(priyam_T)

[ 10.    13.75  17.5   21.25  25.    28.75  32.5   36.25  40.    43.75
  47.5   51.25  55.    58.75  62.5   66.25  70.    73.75  77.5   81.25
  85.    88.75  92.5   96.25 100.  ]


In [67]:
if np.array_equal(priyam,priyam_T):
    print("T does not change the 1D array")
else:
    print("T works for transposing")

T does not change the 1D array


In [69]:
ucs420=np.array([[10,20,30,40],[50,60,70,80],[90,15,20,35]])
print(ucs420)

[[10 20 30 40]
 [50 60 70 80]
 [90 15 20 35]]


In [71]:
mean_value=np.mean(ucs420)
print(mean_value)

43.333333333333336


In [73]:
median_value=np.median(ucs420)
print(median_value)

37.5


In [75]:
max_value=np.max(ucs420)
print(max_value)

90


In [79]:
min_value=np.min(ucs420)
print(min_value)

10


In [81]:
unique_element=np.unique(ucs420)
print(unique_element)

[10 15 20 30 35 40 50 60 70 80 90]


In [87]:
reshaped_ucs420=np.reshape(ucs420,(4,3))
print(reshaped_ucs420)

[[10 20 30]
 [40 50 60]
 [70 80 90]
 [15 20 35]]


In [85]:
resized_ucs420=np.resize(ucs420,(2,3))
print(resized_ucs420)

[[10 20 30]
 [40 50 60]]


In [89]:
reshaped_ucs420=ucs420.reshape(4,3)
print(reshaped_ucs420)

[[10 20 30]
 [40 50 60]
 [70 80 90]
 [15 20 35]]
